adding bitmap class
joesteel/ConnorCodeKata pull request #5
Opened 2022-07-04 21:14 UTC by joesteel

which will be used by the bloonfilter to create arrays of bits and get/set them

2022-07-05 20:09 UTC, joesteel commented
where's my review @akumariiit ???

2022-07-13 19:31 UTC, akumariiit requested changes

2022-07-13 19:31 UTC, akumariiit commented on src/main/java/com/connor/codekata1/BitMap.java
> +        else{
Small but very important point... think about consistency in coding style... my preferred way is

```
if () {
....
} else {
...
}
```

2022-07-13 19:31 UTC, akumariiit commented on src/main/java/com/connor/codekata1/BitMap.java
> +        int bitmask = 1;
bitmask is always 1 so may be declare it as constant at top?

2022-07-13 19:31 UTC, akumariiit commented on src/main/java/com/connor/codekata1/BitMap.java
> +        int result = (word & bitMask);
Always good to declare them as final to avoid accidental mutation if not needed. Can be covered by test but it gives compile time safety

2022-07-13 19:31 UTC, akumariiit commented on src/test/java/com/connor/codekata1/BitMapTest.java
> +        assert (size == 1024 / 32 + 1);
should not it be 
`assertTrue (size == 1024 / 32 + 1)`

or 

`assertEquals (size, 33)`

2022-07-16 17:29 UTC, joesteel commented on src/main/java/com/connor/codekata1/BitMap.java
> +    private static final int ONES = 0xFFFFFFFF;
No where :( Gonna remove

2022-07-16 17:30 UTC, joesteel commented on src/main/java/com/connor/codekata1/BitMap.java
> +    public int getBit(int position){
aaaah... very cool, will change to use that

2022-07-16 17:38 UTC, joesteel commented on src/main/java/com/connor/codekata1/BitMap.java
> +        int exact_position = position%WORD_SIZE;
yep

2022-07-16 17:42 UTC, joesteel commented on src/main/java/com/connor/codekata1/BitMap.java
> +        int bitmask = 1;
I'm mutating it with the bit shifts in the function (so can't be const) and need to ensure it's reset back to 1 every time I use the get/sets so think better to use a new one when entering the funcs...

2022-07-16 17:46 UTC, joesteel commented on src/test/java/com/connor/codekata1/BitMapTest.java
> +        assert (size == 1024 / 32 + 1);
indeed! didn't know standard assert needs a variable to enable them

2022-07-16 17:49 UTC, joesteel commented on src/test/java/com/connor/codekata1/BitMapTest.java
> +        // so every position in the first 32 is a 1 and everything position in the next 64 is a 0
misleading comment, updating

2022-07-28 09:36 UTC, merged